### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by jiyyt** [rastasheep/ubuntu-sshd#10] opened 2017-07-16 22:18 UTC
Is it me or is it not accepting the root password?

```
$ ssh root@127.0.0.1 -p 32770
root@127.0.0.1's password: 
Permission denied, please try again.
```

**Comment by rastasheep** [comment] 2017-11-08 18:36
Have you managed to solve this issue? can you share which tag/version of image are you using? I was not able to reproduce this.

**Comment by OlegJakushkin** [comment] 2018-04-23 16:29
Reproduced for me, on all images 16.04, 18.04. Simple solution add a line `RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config` instead of sed one (it does not add\change anething in `/etc/ssh/sshd_config` for me).

example:
```bash
FROM       ubuntu:18.04
MAINTAINER Aleksandar Diklic "https://github.com/rastasheep"

RUN apt-get update

RUN apt-get install -y openssh-server
RUN mkdir /var/run/sshd

RUN echo 'root:root' |chpasswd

RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config

CMD    ["/usr/sbin/sshd", "-D"]
```

**Comment by ngaro** [comment] 2018-05-10 09:35
This problem is fixed in the current version

**Comment by rastasheep** [comment] 2018-05-10 09:54
If someone experience this again please open new issue, and we'll to investigate/address it there. Also don't forget to pull newest versions of images.

**Closed by rastasheep** 2018-05-10 09:54 UTC
